server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/tls.crt;
    ssl_certificate_key /etc/nginx/certs/tls.key;

    root /usr/share/nginx/html;
    index index.html;

    location /api/v1/clima/ {
        proxy_pass http://clima:8001/api/v1/clima/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /api/v1/afluencia/pronostico {
        proxy_pass http://afluencia:8002/api/v1/afluencia/pronostico;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /api/v1/afluencia/historial {
        auth_basic "Historial administrativo";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://afluencia:8002/api/v1/afluencia/historial;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /health {
        proxy_pass http://afluencia:8002/health;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
